from re import compile as recompile

HTML_TAGS = (
    'a',
    'abbr',
    'acronym',
    'address',
    'applet',
    'area',
    'article',
    'aside',
    'audio',
    'b',
    'base',
    'bdi',
    'bdo',
    'bgsound',
    'big',
    'blink',
    'blockquote',
    'body',
    'br',
    'button',
    'canvas',
    'caption',
    'center',
    'cite',
    'code',
    'col',
    'colgroup',
    'content',
    'data',
    'datalist',
    'dd',
    'del',
    'details',
    'dfn',
    'dialog',
    'dir',
    'div',
    'dl',
    'dt',
    'em',
    'embed',
    'fieldset',
    'figcaption',
    'figure',
    'font',
    'footer',
    'form',
    'frame',
    'frameset',
    'h1',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6',
    'head',
    'header',
    'hgroup',
    'hr',
    'html',
    'i',
    'iframe',
    'image',
    'img',
    'input',
    'ins',
    'kbd',
    'keygen',
    'label',
    'legend',
    'li',
    'link',
    'main',
    'map',
    'mark',
    'marquee',
    'menu',
    'menuitem',
    'meta',
    'meter',
    'nav',
    'nobr',
    'noembed',
    'noframes',
    'noscript',
    'object',
    'ol',
    'optgroup',
    'option',
    'output',
    'p',
    'param',
    'picture',
    'plaintext',
    'portal',
    'pre',
    'progress',
    'q',
    'rb',
    'rp',
    'rt',
    'rtc',
    'ruby',
    's',
    'samp',
    'script',
    'section',
    'select',
    'shadow',
    'slot',
    'small',
    'source',
    'spacer',
    'span',
    'strike',
    'strong',
    'style',
    'sub',
    'summary',
    'sup',
    'table',
    'tbody',
    'td',
    'template',
    'textarea',
    'tfoot',
    'th',
    'thead',
    'time',
    'title',
    'tr',
    'track',
    'tt',
    'u',
    'ul',
    'var',
    'video',
    'wbr',
    'xmp',
)

INPUT_TYPES = (
    'button',
    'checkbox',
    'color',
    'date',
    'datetime-local',
    'email',
    'file',
    'hidden',
    'image',
    'month',
    'number',
    'password',
    'radio',
    'range',
    'reset',
    'search',
    'submit',
    'tel',
    'text',
    'time',
    'url',
    'week',
)

class HtmlComposer:
    KEY_REMOVER = recompile('^[_]+')

    @classmethod
    def format_key(cls, key):
        return KEY_REMOVER.replace(key, '').replace('_', '-')

    @classmethod
    def format_values(cls, value):
        if isinstance(value, (tuple, list)):
            return ' '.join(str(s) for s in value)
        if value is None or isinstance(value, bool):
            return value
        return str(value)

    @classmethod
    def prepare_attrs(cls, kwargs):
        return {k: cls.format_values(v) for k, v in kwargs.items() if v is not None and v is not False}

    @classmethod
    def key_value_formatter(cls, key, value):
        return f'{format_key(key)}="{{{key}}}"'

    @class
    def format_attrs(cls, kwargs):
        kwargs = cls.prepare_attrs(kwargs)
        return ' '.join(cls.format_key(k) if v is True else cls.key_value_formatter(k, v) for k, v in kwargs.items())

    @class
    def format_begin_tag(cls, _tag_name, **kwargs):
        return format_html()
